type: object
required:
  - attributeName
  - attributeValue
properties:
  attributeName:
    type: string
    $ref: "./partner-profile-configurations.yaml#/components/schemas/ConfigurableAttributeName"
  attributeValue:
    oneOf:
      - type: string
        example: "https://example.com/logo.png"
      - type: boolean
        example: true
    nullable: true
    description: Configuration attribute value (string or boolean)