type: object
required:
  - attributeName
  - attributeValue
properties:
  attributeName:
    type: string
    enum:
      - logoUrl
      - supportEmail
      - supportUrl
      - email.kycConfirmation.successBanner.url
      - email.xpayConfirmation.applePayBanner.url
      - email.xpayConfirmation.googlePayBanner.url
      - email.kycConfirmation.cardActivation.url
      - email.kyc.enabled
    description: Configuration attribute name
  attributeValue:
    oneOf:
      - type: string
      - type: boolean
    nullable: true
    description: Configuration attribute value (string or boolean)
    examples:
      - "https://example.com/logo.png"
      - "support@partner.com"
      - "https://partner.com/support"
      - true