components:
  schemas:
    PartnerProfileProperties:
      type: object
      properties:
        accountId:
          type: string
          description: The unique identifier of the partner account
          example: "225d85e65495722bf6517ea0ba0d6f56"
        createdAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp when the partner profile was created
          example: "2023-10-14T10:30:00.000Z"
        modifiedAt:
          type: string
          format: date-time
          description: ISO 8601 timestamp when the partner profile was last modified
          example: "2023-10-14T15:45:30.000Z"
        isKycStatementsSubmissionAllowed:
          type: boolean
          description: Whether KYC statements submission is allowed for this partner
          example: true
        logoUrl:
          type: string
          nullable: true
          description: URL to the partner's logo image
          example: "https://example.com/logo.png"
        supportEmail:
          type: string
          nullable: true
          description: Support email address for the partner
          example: "support@partner.com"
        email.kyc.enabled:
          type: boolean
          nullable: true
          description: Whether KYC email notifications are enabled for this partner
          example: true
        email.kycConfirmation.cardActivation.url:
          type: string
          nullable: true
          description: URL for the card activation banner in KYC confirmation emails
          example: "https://example.com/kyc-card-activation.png"
        email.kycConfirmation.successBanner.url:
          type: string
          nullable: true
          description: URL for the success banner in KYC confirmation emails
          example: "https://example.com/kyc-success.png"
        email.xpayConfirmation.applePayBanner.url:
          type: string
          nullable: true
          description: URL for the Apple Pay banner in xPay confirmation emails
          example: "https://example.com/apple-pay.png"
        email.xpayConfirmation.googlePayBanner.url:
          type: string
          nullable: true
          description: URL for the Google Pay banner in xPay confirmation emails
          example: "https://example.com/google-pay.png"
        supportUrl:
          type: string
          nullable: true
          description: URL to the partner's support page
          example: "https://partner.com/support"

    ConfigurableAttributeName:
      type: string
      enum:
        - logoUrl
        - supportEmail
        - supportUrl
        - email.kycConfirmation.successBanner.url
        - email.xpayConfirmation.applePayBanner.url
        - email.xpayConfirmation.googlePayBanner.url
        - email.kycConfirmation.cardActivation.url
        - email.kyc.enabled
      description: Configuration attribute name