post:
  tags:
    - client-application
  summary: Update Allowed Origins
  operationId: update-allowed-origins
  description: |
    Add url origins to the client application whitelist.
    The [Initiate Login](/api-reference/initiate-login) endpoint will reject non-whitelisted origins.
    **Warning!** This is a destructive operation. The allowed origins will be overwritten with the provided list.
    Use the [Get Client Application](/api-reference/get-client-application) endpoint to retrieve the current list of allowed origins.
  parameters:
    - name: clientApplicationId
      in: path
      description: Id of the client application.
      example: 65a7e8ef0d230d0a6bf755e07d39eb02
      required: true
      schema:
        type: string
  requestBody:
    content:
      application/json:
        schema:
          $ref: "./models/client-application-update-origins-request.yaml"
    required: true
  responses:
    '204':
      description: No content
      content:
        application/json: {}
    '403':
      description: |
          Subject is not allowed to perform the action with the reason stated in the `errorCode`

          **FORBIDDEN**
          Resource does not exist or there are no sufficient permissions to perform the action.
      content:
        application/json:
          schema:
            $ref: '../../models/api-error-403.yaml'
    '400':
      description: Request parameters are invalid
      content:
        application/json:
          schema:
            $ref: '../../models/api-error-400.yaml'
