tags:
  - fault-configs
summary: Delete Fault Config
operationId: delete-fault-config
description: Deletes the configuration of the fault type for the identified account.
parameters:
  - name: accountId
    in: path
    description: ID of the account to delete the configuration for.
    example: e4b66d1ddecbf518f5f337n5e5a4f682
    required: true
    schema:
      type: string
  - name: faultTypeName
    in: path
    description: The name of the fault type to delete the configuration for.
    example: approval-funding-submit-transfer-error
    required: true
    schema:
      type: string
      enum:
        - approval-funding-submit-transfer-error
responses:
  "403":
    description: |
      **FAULT CONFIGS NOT FOUND**
      The fault config for the specified account and fault type was not found.
    content:
      application/json:
        schema:
          $ref: "../../models/api-error-403.yaml"
  "400":
    description: Request fields are invalid
    content:
      application/json:
        schema:
          $ref: "../../models/api-error-400.yaml"
