tags:
  - fault-configs
summary: Set Fault Config
operationId: set-fault-config
description: Creates or replaces the configuration of the fault type for the identified account.
parameters:
  - name: accountId
    in: path
    description: ID of the account to set the fault configuration for.
    example: e4b66d1ddecbf518f5f337n5e5a4f682
    required: true
    schema:
      type: string
  - name: faultTypeName
    in: path
    description: The name of the fault type to set the configuration for.
    example: approval-funding-submit-transfer-error
    required: true
    schema:
      type: string
      enum:
        - approval-funding-submit-transfer-error
requestBody:
  content:
    application/json:
      schema:
        type: object
        properties:
          value:
            type: string
            description: The value to set for the fault type. Accepts a string, number (as a string), or boolean (as a string), as required by the referenced fault type.
            example: "true"
responses:
  "200":
    description: Successful operation
    content:
      application/json:
        schema:
          $ref: "./models/fault-configs-response.yaml"
  "400":
    description: |
      **FAULT_VALUE_TYPE_INCORRECT**
      The value type is incorrect.
    content:
      application/json:
        schema:
          $ref: "../../models/api-error-400.yaml"
  "403":
    description: |
      **FAULT_TYPE_INVALID**
      The fault type is invalid.

      **FAULT_CONFIG_NOT_ALLOWED**
      The account is not allowed to set fault configurations.
    content:
      application/json:
        schema:
          $ref: "../../models/api-error-403.yaml"
