openapi: 3.1.0
info:
  version: 1.0.0
  title: Immersve Webhooks
tags:
  - name: kyc
    x-displayName: KYC
  - name: payments
    x-displayName: Payments
  - name: xpay
    x-displayName: XPay
  - name: test-webhooks
    x-displayName: Test Webhooks

# Custom attribute used as YAML anchor to simplify webhook header inclusion
x-webhook-headers: &WebhookHeaders
  - $ref: "#/components/parameters/XDeliveryId"
  - $ref: "#/components/parameters/XKeyId"
  - $ref: "#/components/parameters/XSignature"

paths: []

components:

  parameters:
    XDeliveryId:
      name: X-Delivery-ID
      in: header
      description: Unique message id plus delivery attempt.
      schema:
        type: string
    XKeyId:
      name: X-Key-ID
      in: header
      description: ID of the public key used to validate the signature.
      schema:
        type: string
    XSignature:
      name: X-Signature
      in: header
      description: >
        Base64-encoded RSA SHA-256 signature of `{deliveryId}:{keyId}:{requestBody}`.
      schema:
        type: string

webhooks:

  xpay-otp:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/xpay-card-load-otp-webhook.yaml }
  xpay-confirmed:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/xpay-card-load-confirmed-webhook.yaml }
  kyc-succeeded:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/kyc-succeeded-webhook.yaml }
  kyc-failed:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/kyc-failed-webhook.yaml }
  kyc-pending:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/kyc-pending-webhook.yaml }
  3ds-otp:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/payment-3ds-otp-webhook.yaml }
  async-test:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/async-test-webhook.yaml }
  transactional-test:
    parameters: *WebhookHeaders
    post: { $ref: ./webhooks/transactional-test-webhook.yaml }
