name: Test deployment

on:
  pull_request:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ steps.deploy-summary.outputs.deploy_url }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Test build website
        run: npm run build
      - run: scripts/netlify-deploy.sh --branch ${{ github.ref_name }} --dir build
        env:
          NETLIFY_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
      - id: deploy-summary
        run: scripts/github-deploy-summary.sh | tee $GITHUB_OUTPUT >> $GITHUB_STEP_SUMMARY
